### ISSUE TITLE
looking forward to see this awesome widget in jcenter/maven

### ISSUE THREAD

**Issue by zhangchaoxu** [linger1216/labelview#14]
Thanks for your great job.
Looking forward to see this awesome widget in jcenter/maven, and I can integrate LabView with gradle.

Thanks

**Comment by linger1216** [comment]
thanks, please wait a few days...  :)

**Comment by smeegoan** [comment]
You can also use it directly from [jitpack](https://jitpack.io/#linger1216/labelview)

**Comment by linger1216** [comment]
thanks, i'll try tonight~~~

**Comment by linger1216** [comment]
@smeegoan tks buddy, already add gradle maven support.
