### ISSUE TITLE
Problem in Base Adapter

### ISSUE THREAD

**Issue by Baawaaji** [linger1216/labelview#2]
label.setTargetView(convertView.findViewById(R.id.featured_icon_row_image), 15, LabelView.Gravity.LEFT_TOP);

on some items it shows perfect label  and on some items it show horizontal Label.

**Comment by linger1216** [comment]
can you give me an issue screenshot ?

**Comment by linger1216** [comment]
I got this problem, because addOnGlobalLayoutListener method is not callback immediately.
I'll add another method later (now is Chinese New Year, so.... )
please wait some days.

**Comment by shaunidiot** [comment]
Having this problem as well. http://i.imgur.com/XQKD0db.png

Waiting for update. Happy Chinese New Year to you! (I'm celebrating as well :+1: )

**Comment by linger1216** [comment]
please check ListViewActivity example

**Comment by Baawaaji** [comment]
Thank you :) and sorry i didnt provide screenshot on time.
