### ISSUE TITLE
¿ How to remove ?

### ISSUE THREAD

**Issue by seba123neo** [linger1216/labelview#3]
I need to remove from the view please...

great control by the way !!!

**Comment by linger1216** [comment]
Thank you for your star.  :) 
Now is Chinese New Year, I'm on vacation, I will add remove method some days later.
Then please check.

**Comment by DonManfred** [comment]
>Thank you for your star. :) 
Got another one :-)
Watching for these change. Thank you for this lib btw! REALLY GREAT

**Comment by linger1216** [comment]
use LabelView remove method. 

please check example. haha

**Comment by haskellcamargo** [comment]
+1. `.remove()` method is not working properly.
