### ISSUE TITLE
view problem

### ISSUE THREAD

**Issue by d7coders** [linger1216/labelview#6]
Hi, after made label for lazy adapter
as you can see in the image link the last image have 2 labels which I just made one label like the other image's label ,but after scrolling up and down this happening 

http://s7.postimg.org/evktvm6gb/Untitled.jpg

**Comment by linger1216** [comment]
do you check ListViewActivity.java file ? 
do you call setID function?

**Comment by linger1216** [comment]
do you check ListViewActivity.java file ? 
do you call setID function?

**Comment by d7coders** [comment]
yes, the code is work , the problem is that when scroll up and down the label position changed , as you see in the image link , the last image's label not in the corner

**Comment by linger1216** [comment]
sorry, Can you share your code? I want to debug...    - -||

**Comment by d7coders** [comment]
public View getView(final int position, View convertView, ViewGroup parent) {
        View vi=convertView;
        if(convertView==null)
            vi = inflater.inflate(R.layout.listview, null);
 
        ImageView image=(ImageView)vi.findViewById(R.id.imageView1);
        
        
        imageLoader.DisplayImage(data[position], image);
        
        LabelView label = new LabelView(activity.getApplicationContext());
        if(!off[position].equals("0")){
         label.setId(12345);
         label.setText(off[position]+"%");
         
         label.setBackgroundColor(0xffcc0000);
         label.setTargetView(vi.findViewById(R.id.imageView1), 15, LabelView.Gravity.RIGHT_TOP);
        }  
        
       
        return vi;
    }

**Comment by d7coders** [comment]
any solution ?

**Comment by linger1216** [comment]
you always create a new label view object.

if labelview has id, you need reuse it. dont create it. for eg:

LabelView label = holder.getView(your id);
if (label == null) {
    label = new LabelView(ListViewActivity.this);
    label.setId(your id);
}

// write something
// label.setText(item.label);
//
