### ISSUE TITLE
Use in XML

### ISSUE THREAD

**Issue by patelakshay13890** [linger1216/labelview#7]
How can I use this view in XML for static use instead of dynamic creating view ??

**Comment by linger1216** [comment]
Sorry, view in xml is not supported. 
Perhaps one day I'll write.

**Comment by patelakshay13890** [comment]
How can I use this in RecyclerVIew by using adapter using
RecyclerVIewViewHolder ??
Not in listview

**Comment by linger1216** [comment]
already supported xml, But you have to change your code. I'm sorry about that.
