### ISSUE TITLE
Use in RecyclerView

### ISSUE THREAD

**Issue by patelakshay13890** [linger1216/labelview#8]
How can I use this in RecyclerVIew by using adapter using RecyclerVIewViewHolder ??
waiting for response...

**Comment by linger1216** [comment]
I will give you eg later....  :) 

 ( cuz too much work recently )

**Comment by patelakshay13890** [comment]
How can I use this in RecyclerVIew by using adapter using RecyclerVIewViewHolder ??
waiting for response...

**Comment by linger1216** [comment]
I try RecyclerVIew right now, sorry, It has bug.I can not be solved temporarily.
Maybe I need extend ImageView to fix it, but it takes a lot of time.

you can use textview in your item xml file, and rotating manually in RecyclerVIew, You can refer to calcOffset function.

**Comment by patelakshay13890** [comment]
ok & thanx for response...

**Comment by patelakshay13890** [comment]
How can I use this in RecyclerVIew by using adapter using RecyclerVIewViewHolder ??
waiting for response...

**Comment by bluemix** [comment]
the same problem is here, having problems with it in the RecyclerView.

**Comment by hishamBakr** [comment]
I have the same problem

**Comment by dyguests** [comment]
I have the same problem...... O  O~~?

**Comment by wsw87201326** [comment]
I have the same problem

**Comment by BishwajitNepali** [comment]
linger1216 :+1:  I am having same problem in recyclerview..hoping you will solve it soon

**Comment by linger1216** [comment]
now i try to fix bug. LOL

**Comment by BishwajitNepali** [comment]
Happy New Year 2016.

**Comment by linger1216** [comment]
already fix bug, But you have to change your code. I'm sorry about that.
